[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
BracketingNonlinearSolve = "70df07ce-3d50-431d-a3e7-ca6ddb60ac1e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
RunwayLib = "c31d23ff-e9b5-4186-8ef8-ce4d62614c67"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tau = "c544e3c2-d3e5-5802-ac44-44683f340e4a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulLinearAlgebra = "c14bd059-d406-4571-8f61-9bd20e53c30b"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
BonitoBook = {url = "http://github.com/SimonDanisch/BonitoBook.jl"}
