[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
RunwayLib = "c31d23ff-e9b5-4186-8ef8-ce4d62614c67"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Typstry = "f0ed7684-a786-439e-b1e3-3b82803b501e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ProfileCanvas = "0.1.7"
Documenter = "1"
DocumenterCitations = "1"
Typstry = "0.6"
