name: Benchmark this PR
on:
  pull_request:
    branches: [ master ]  # change to your default branch
permissions:
  contents: read
  pull-requests: write    # needed to post comments

jobs:
  bench:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          enable-plots: true
